import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/Sidebar';
import Subnav from '../components/subnav';
import CarouselContent from '../components/Carousel';
import Products from '../components/Products';
export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <header>
        <nav className="navbars">
          <Header />
          <Subnav />
        </nav>
      </header>
      <article>
        <section id="carousel">
          <CarouselContent />
        </section>
        <section id="Products">
          <Products />
        </section>
      </article>
    </main>
  );
}
