import { useState } from "react";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HomePage from "../components/home/index";
import Header from "../components/home/Sidebar";
import Subnav from "../components/home/subnav";

import axios from "axios";

import baseUrl from "../utils/baseUrl";

function Home({ user, productsData, errorLoading }) {
  const [products, setProducts] = useState(productsData);

  return (
    <main>
      <Head>
        <title>Huassy ||Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <header>
        <nav className="navbars">
          <Header />
          <Subnav />
        </nav>
      </header>
      <HomePage />
    </main>
  );
}

// export const getServerSideProps = async (ctx) => {
Home.getInitialProps = async (ctx) => {
  try {
    const res = await axios.get(`${baseUrl}/api/products`);
    // console.log(res.data)
    return { productsData: res.data };
  } catch (error) {
    return { errorLoading: true };
  }
};

export default Home;
